from __future__ import annotations

from dataclasses import dataclass

from .domain import BodyPoint, BodyState, HitQuality, NoteKind


# Occupancy still determines whether a note is hit at all; these only control the
# optional GREAT/PERFECT timing bonus.
PERFECT_WINDOW_SECONDS = 0.10
GREAT_WINDOW_SECONDS = 0.30
MOTION_EVENT_LOCKOUT_SECONDS = 0.16
MOTION_REARM_SECONDS = 0.07
MOTION_EVENT_VISUAL_SECONDS = 0.80

# Signed vertical velocity in normalized image coordinates per second. Image Y
# increases downward: wrists strike upward (negative dy), knees strike downward
# (positive dy). Values are deliberately isolated for easy webcam tuning.
# Deliberately sensitive: in-lane gestures should be easy to register. False
# positives are preferable to a stomp/punch that feels correctly timed but is
# ignored. Lockout and directional re-arm still suppress repeated triggers.
HAND_STRIKE_SPEED = 0.24
HAND_RESET_SPEED = 0.12
KNEE_STRIKE_SPEED = 0.20
KNEE_RESET_SPEED = 0.10


@dataclass
class MotionEvent:
    kind: NoteKind
    lane: int
    song_time: float
    limb: str
    strength: float
    source: str = "motion"
    consumed: bool = False


@dataclass
class _LimbState:
    point: BodyPoint | None = None
    body_timestamp: float = 0.0
    vertical_velocity_ema: float = 0.0
    armed: bool = True
    last_event_body_time: float = -999.0


class MotionTracker:
    """Turn lane changes and directional limb movement into sparse impulses.

    Horizontal position chooses the lane. Vertical movement provides the timing
    gesture while remaining in that lane: wrists strike upward; knees strike
    downward. Lane entry is independently a valid deliberate timing action.

    This never decides whether a note is hit. It only emits optional timing
    events that can upgrade an occupancy HIT to GREAT/PERFECT.
    """

    def __init__(self) -> None:
        self._states = {name: _LimbState() for name in ("lw", "rw", "lk", "rk")}
        self._events: list[MotionEvent] = []
        self._last_body_timestamp = -1.0

    def reset(self) -> None:
        self._states = {name: _LimbState() for name in ("lw", "rw", "lk", "rk")}
        self._events.clear()
        self._last_body_timestamp = -1.0

    @staticmethod
    def _limbs(body: BodyState):
        return (
            ("lw", NoteKind.HANDS, body.left_wrist),
            ("rw", NoteKind.HANDS, body.right_wrist),
            ("lk", NoteKind.FOOT, body.left_knee),
            ("rk", NoteKind.FOOT, body.right_knee),
        )

    @staticmethod
    def _strike_speed(kind: NoteKind, vertical_velocity: float) -> float:
        # Image Y grows downward. Upward wrist velocity is negative; downward
        # knee velocity is positive. Opposite-direction motion contributes zero.
        if kind == NoteKind.HANDS:
            return max(0.0, -vertical_velocity)
        return max(0.0, vertical_velocity)

    def update(self, body: BodyState, song_time: float | None) -> list[MotionEvent]:
        """Observe a new pose sample and return events generated by that sample.

        MediaPipe results arrive slower than the render loop, so repeated frames
        with the same BodyState timestamp are ignored.
        """
        if body.timestamp <= 0.0 or body.timestamp == self._last_body_timestamp:
            return []
        self._last_body_timestamp = body.timestamp
        generated: list[MotionEvent] = []

        for name, kind, point in self._limbs(body):
            state = self._states[name]
            previous = state.point
            prev_time = state.body_timestamp

            # Lane entry is its own deliberate action and always gets an input
            # event/visual pulse. It does not require leaving the playfield, only
            # a change in the resolved horizontal lane.
            entered_lane = (
                song_time is not None
                and point.visible
                and point.lane is not None
                and previous is not None
                and previous.visible
                and previous.lane is not None
                and previous.lane != point.lane
            )

            if (
                previous is not None
                and previous.visible
                and point.visible
                and prev_time > 0.0
                and body.timestamp > prev_time
            ):
                instantaneous_vy = (point.y - previous.y) / max(body.timestamp - prev_time, 1e-4)
                state.vertical_velocity_ema = 0.45 * state.vertical_velocity_ema + 0.55 * instantaneous_vy
            else:
                state.vertical_velocity_ema *= 0.35

            strike_threshold = HAND_STRIKE_SPEED if kind == NoteKind.HANDS else KNEE_STRIKE_SPEED
            reset_threshold = HAND_RESET_SPEED if kind == NoteKind.HANDS else KNEE_RESET_SPEED
            strike_speed = self._strike_speed(kind, state.vertical_velocity_ema)
            since_event = body.timestamp - state.last_event_body_time

            event: MotionEvent | None = None
            if entered_lane:
                # A true lane transition is naturally debounced by the lane
                # resolver. Treat it as immediate feedback and a valid timing
                # signal even if another motion event happened recently.
                event = MotionEvent(
                    kind=kind,
                    lane=int(point.lane),
                    song_time=float(song_time),
                    limb=name,
                    strength=max(1.0, strike_speed / max(strike_threshold, 1e-6)),
                    source="entry",
                )
                state.armed = False
            elif (
                song_time is not None
                and state.armed
                and point.visible
                and point.lane is not None
                and strike_speed >= strike_threshold
                and since_event >= MOTION_EVENT_LOCKOUT_SECONDS
            ):
                event = MotionEvent(
                    kind=kind,
                    lane=int(point.lane),
                    song_time=float(song_time),
                    limb=name,
                    strength=strike_speed / strike_threshold,
                    source="strike",
                )
                state.armed = False

            if event is not None:
                state.last_event_body_time = body.timestamp
                self._events.append(event)
                generated.append(event)

            # Directional re-arm: after an upward wrist strike, slowing or
            # moving downward makes strike_speed collapse toward zero; after a
            # downward knee strike, slowing or lifting the knee does the same.
            # This prevents one continuous sweep from generating many events.
            if (
                event is None
                and not state.armed
                and since_event >= MOTION_REARM_SECONDS
                and strike_speed <= reset_threshold
            ):
                state.armed = True

            state.point = point
            state.body_timestamp = body.timestamp

        if song_time is not None:
            cutoff = song_time - (GREAT_WINDOW_SECONDS + 0.50)
            self._events = [e for e in self._events if not e.consumed and e.song_time >= cutoff]
        return generated

    def match(self, kind: NoteKind, lanes: tuple[int, ...], note_time: float) -> tuple[HitQuality, float] | None:
        """Consume one event per required lane and return timing quality/delta.

        For a two-hand target, both required hand lanes need their own fresh
        impulse. One physical motion event can never grade two notes.
        """
        chosen: list[MotionEvent] = []
        used_ids: set[int] = set()
        for lane in lanes:
            candidates = [
                e
                for e in self._events
                if not e.consumed
                and id(e) not in used_ids
                and e.kind == kind
                and e.lane == lane
                and abs(e.song_time - note_time) <= GREAT_WINDOW_SECONDS
            ]
            if not candidates:
                return None
            event = min(candidates, key=lambda e: abs(e.song_time - note_time))
            chosen.append(event)
            used_ids.add(id(event))

        worst_delta = max(abs(e.song_time - note_time) for e in chosen)
        quality = HitQuality.PERFECT if worst_delta <= PERFECT_WINDOW_SECONDS else HitQuality.GREAT
        for event in chosen:
            event.consumed = True
        self._events = [e for e in self._events if not e.consumed]
        return quality, worst_delta

    @property
    def pending_events(self) -> tuple[MotionEvent, ...]:
        return tuple(self._events)
